name: Test Runner

on:
  push:
    branches: [main, add-ci]
  pull_request:
    branches:
    - main
  workflow_dispatch:
      
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check compilation
        run: make emulator
